#!/usr/bin/env bb

;; Project acceptance entrypoint generator.
;;
;;   acceptance-entrypoint-generator [--feature-path <path>] <json-ir> <generated-test-output>
;;
;; Reads parser JSON IR and writes a JUnit entry point that hands the IR to the
;; acceptance runtime. The entry point embeds the IR; it never reads the source
;; feature file.
;;
;; Exit codes: 0 generated, 1 input/output error, 2 usage error.

(ns acceptance-entrypoint-generator
  (:require [babashka.fs :as fs]
            [cheshire.core :as json]
            [clojure.string :as str])
  (:import [java.security MessageDigest]))

(def package "the.monopoly.game.specs.acceptance.generated")

(defn- die! [status message]
  (binding [*out* *err*] (println message))
  (System/exit status))

(defn- class-name [ir-path]
  (let [stem (-> (fs/file-name ir-path) (str/replace #"\.json$" ""))]
    (->> (str/split stem #"[^A-Za-z0-9]+")
         (remove str/blank?)
         (map str/capitalize)
         (str/join)
         (#(str % "AcceptanceTest")))))

(defn- metadata-name [feature-path]
  (-> (str/lower-case feature-path)
      (str/replace #"[^a-z0-9]+" "-")
      (str/replace #"^-+|-+$" "")
      (str ".json")))

(defn- java-string [value]
  (str \" (-> value
              (str/replace "\\" "\\\\")
              (str/replace "\"" "\\\"")
              (str/replace "\n" "\\n")
              (str/replace "\r" "\\r"))
       \"))

(defn- step->java [{:keys [keyword text]}]
  (format "new Ir.Step(%s, %s)" (java-string keyword) (java-string text)))

(defn- example->java [example]
  (if (empty? example)
    "Map.of()"
    (format "Map.ofEntries(%s)"
            (->> (sort-by key example)
                 (map (fn [[k v]] (format "Map.entry(%s, %s)" (java-string (name k)) (java-string v))))
                 (str/join ", ")))))

(defn- list-of [items]
  (if (empty? items) "List.of()" (format "List.of(\n%s\n" (str/join ",\n" items))))

(defn- indent [level text]
  (->> (str/split-lines text)
       (map #(if (str/blank? %) % (str (apply str (repeat level "  ")) %)))
       (str/join "\n")))

(defn- scenario->java [{:keys [name steps examples]}]
  (format "new Ir.Scenario(\n  %s,\n  %s,\n  %s)"
          (java-string name)
          (if (empty? steps)
            "List.of()"
            (format "List.of(\n%s)" (indent 2 (str/join ",\n" (map step->java steps)))))
          (if (empty? examples)
            "List.of()"
            (format "List.of(\n%s)" (indent 2 (str/join ",\n" (map example->java examples)))))))

(defn- render [ir ir-path]
  (let [scenarios (->> (:scenarios ir)
                       (map scenario->java)
                       (map #(indent 3 %))
                       (str/join ",\n"))
        background (if (empty? (:background ir))
                     "List.of()"
                     (format "List.of(\n%s)"
                             (indent 5 (str/join ",\n" (map step->java (:background ir))))))]
    (str "// Generated by acceptance-entrypoint-generator from " (fs/file-name ir-path) ".\n"
         "// Do not edit; regenerate with acceptance/run-acceptance.sh.\n"
         "package " package ";\n\n"
         "import org.junit.jupiter.api.DynamicTest;\n"
         "import org.junit.jupiter.api.TestFactory;\n"
         "import the.monopoly.game.specs.acceptance.AcceptanceRuntime;\n"
         "import the.monopoly.game.specs.acceptance.Ir;\n"
         "import the.monopoly.game.specs.acceptance.MonopolyStepHandlers;\n\n"
         "import java.util.List;\n"
         "import java.util.Map;\n"
         "import java.util.stream.Stream;\n\n"
         "class " (class-name ir-path) " {\n"
         "  private static final Ir FEATURE = new Ir(\n"
         "      " (java-string (:name ir)) ",\n"
         "      " (str/replace background #"\n" "\n      ") ",\n"
         "      List.of(\n" scenarios "));\n\n"
         "  @TestFactory\n"
         "  Stream<DynamicTest> acceptance() {\n"
         "    return new AcceptanceRuntime(MonopolyStepHandlers.handlers()).execute(FEATURE);\n"
         "  }\n"
         "}\n")))

(defn- sha256 [text]
  (->> (.digest (MessageDigest/getInstance "SHA-256") (.getBytes text "UTF-8"))
       (map #(format "%02x" %))
       (apply str)))

(defn -main [& args]
  (let [[flags positional] (loop [remaining args flags {} positional []]
                             (cond
                               (empty? remaining) [flags positional]
                               (= "--feature-path" (first remaining))
                               (recur (drop 2 remaining) (assoc flags :feature-path (second remaining)) positional)
                               :else (recur (rest remaining) flags (conj positional (first remaining)))))
        [ir-path out-dir] positional]
    (when-not (= 2 (count positional))
      (die! 2 "usage: acceptance-entrypoint-generator [--feature-path <path>] <json-ir> <generated-test-output>"))
    (when-not (fs/exists? ir-path)
      (die! 1 (str "No such JSON IR: " ir-path)))

    (try
      (let [ir (json/parse-string (slurp ir-path) true)
            source (render ir ir-path)
            package-dir (fs/path out-dir (str/replace package "." fs/file-separator))
            java-file (fs/path package-dir (str (class-name ir-path) ".java"))
            feature-path (:feature-path flags ir-path)
            metadata-file (fs/path out-dir "metadata" (metadata-name feature-path))]
        (fs/create-dirs package-dir)
        (spit (str java-file) source)
        (fs/create-dirs (fs/parent metadata-file))
        (spit (str metadata-file)
              (json/generate-string
                {:schema_version 1
                 :feature_path feature-path
                 :ir_path (str ir-path)
                 :implementation_hash (str "sha256:" (sha256 source))
                 :hash_scope "generated_files"
                 :generated_files [(str java-file)]}
                {:pretty true}))
        (println "generated" (str java-file))
        (System/exit 0))
      (catch Exception cause
        (die! 1 (str "Failed to generate from " ir-path ": " (ex-message cause)))))))

(apply -main *command-line-args*)
